### ISSUE TITLE
Configured id value from options object is never used

### ISSUE THREAD

**Issue by Protoss78** [KapMug/feathers-cradle-couchdb#3]
When creating the service the configured id field is remembered but later on never used. The code always does hardcoded checks for _id or id fields.

**Comment by bazaglia** [comment]
I advise you to not use this adapter. If you need a couchdb database adapter for feathers that is functional and reliable for production, please check http://github.com/kapmug/feathers-nano

Please note it's not documented yet and there are still missing features to be implemented, like support pagination both on and off (for now it always assume pagination is on) and the ID field is not configurable (always use `_id` which is the standard for couchdb).

If you need extra features feel free to open issues and/or PR's in the `feathers-nano` project.

**Comment by Protoss78** [comment]
Thanks for the tip. Yesterday I've learned the hard way that none of the feathers-couchdb adapters out there really works. Will try feathers-nano as soon as possible.
